### ISSUE TITLE
API request failed error with new panel for environment creation

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/tljh-repo2docker#8]
After upgrading TLJH installation of PlasmaBio, I got the new panel for environement creation :smile: 

![image](https://user-images.githubusercontent.com/733861/80726782-23351480-8b05-11ea-8e85-6aeb5e020d44.png)

I tried to create a new environment but encountered an error:

![image](https://user-images.githubusercontent.com/733861/80726831-3811a800-8b05-11ea-9dfc-64d997d58c82.png)

After a click on OK, I got 

![image](https://user-images.githubusercontent.com/733861/80726868-46f85a80-8b05-11ea-9de3-8e08d4bde125.png)

that seems running forever.

Did I miss something while upgrading TLJH installation (with TLJH-repo2docker plugin)?

**Comment by jtpio** [comment]
Nice :)

Maybe a good opportunity to look at logs: https://docs.plasmabio.org/en/latest/troubleshooting/index.html#looking-at-logs

**Comment by jtpio** [comment]
The issue might come from the browser cache that still uses the old assets.

Since the JS has changed it would be good to try after clearing the cache.

**Comment by pierrepo** [comment]
>Maybe a good opportunity to look at logs

Oh yes...

```
$ sudo journalctl -u jupyterhub | tail -n 20
Apr 30 15:38:59 plasmabio-pierrepo-test-2 python3[18482]: [E 2020-04-30 15:38:59.529 JupyterHub log:174] 503 GET /hub/user/claire/toto/metrics?1588261139494 (claire@82.254.29.234) 6.50ms
Apr 30 15:39:04 plasmabio-pierrepo-test-2 python3[18482]: [I 2020-04-30 15:39:04.566 JupyterHub log:174] 302 GET /user/claire/toto/metrics?1588261144527 -> /hub/user/claire/toto/metrics?1588261144527 (@82.254.29.234) 2.26ms
Apr 30 15:39:04 plasmabio-pierrepo-test-2 python3[18482]: [I 2020-04-30 15:39:04.567 JupyterHub log:174] 302 GET /user/claire/toto/metrics?1588261144557 -> /hub/user/claire/toto/metrics?1588261144557 (@82.254.29.234) 2.39ms
Apr 30 15:39:04 plasmabio-pierrepo-test-2 python3[18482]: [E 2020-04-30 15:39:04.583 JupyterHub log:174] 503 GET /hub/user/claire/toto/metrics?1588261144557 (claire@82.254.29.234) 5.65ms
Apr 30 15:39:04 plasmabio-pierrepo-test-2 python3[18482]: [E 2020-04-30 15:39:04.588 JupyterHub log:174] 503 GET /hub/user/claire/toto/metrics?1588261144527 (claire@82.254.29.234) 4.95ms
Apr 30 15:39:05 plasmabio-pierrepo-test-2 python3[18482]: [I 2020-04-30 15:39:05.792 JupyterHub log:174] 302 GET /user/claire/toto/api/contents/?content=1&1588261145775 -> /hub/user/claire/toto/api/contents/?content=1&1588261145775 (@82.254.29.234) 1.60ms
Apr 30 15:39:05 plasmabio-pierrepo-test-2 python3[18482]: [W 2020-04-30 15:39:05.812 JupyterHub base:1262] Failing suspected API request to not-running server: /hub/user/claire/toto/api/contents/
Apr 30 15:39:05 plasmabio-pierrepo-test-2 python3[18482]: [E 2020-04-30 15:39:05.813 JupyterHub log:174] 503 GET /hub/user/claire/toto/api/contents/?content=1&1588261145775 (claire@82.254.29.234) 5.16ms
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]: [E 200430 15:39:57 web:1792] Uncaught exception POST /services/environments/api/build (127.0.0.1)
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:     HTTPServerRequest(protocol='http', host='dev.plasmabio.org', method='POST', uri='/services/environments/api/build', version='HTTP/1.1', remote_ip='127.0.0.1')
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:     Traceback (most recent call last):
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/web.py", line 1703, in _execute
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:         result = await result
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:       File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:         result = self.fn(*self.args, **self.kwargs)
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:       File "/opt/tljh/hub/lib/python3.6/site-packages/tljh_repo2docker/builder.py", line 135, in post
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:         display_name = data["displayName"]
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]:     KeyError: 'displayName'
Apr 30 15:39:57 plasmabio-pierrepo-test-2 python3[18482]: [E 200430 15:39:57 web:2250] 500 POST /services/environments/api/build (127.0.0.1) 4.12ms
Apr 30 15:39:59 plasmabio-pierrepo-test-2 python3[18482]: [I 2020-04-30 15:39:59.166 JupyterHub log:174] 200 GET /hub/api/users (cull-idle@51.68.113.239) 17.39ms


```

**Comment by pierrepo** [comment]
> Since the JS has changed it would be good to try after clearing the cache.

Bloody cache...

It is now working like a charm. Sorry for that :disappointed: 

![image](https://user-images.githubusercontent.com/733861/80730647-1d8dfd80-8b0a-11ea-84bc-74defac79553.png)
